---
kind: pipeline
type: docker
name: default

steps:
  - name: Override
    image: node
    environment:
      DRONE_AUTH_TOKEN:
        from_secret: drone_auth_token
    commands:
      - bash prebuild.sh
  - name: Restore Cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ checksum "package.json" }}'
      archive_format: "gzip"
      mount:
        - "./node_modules"

    volumes:
      - name: cache
        path: /tmp/cache

  - name: Build
    image: node
    commands:
      - yarn install
      - yarn build

  - name: Rebuild Cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ checksum "package.json" }}'
      archive_format: "gzip"
      mount:
        - "./node_modules"
    volumes:
      - name: cache
        path: /tmp/cache

  - name: Deploy
    image: node
    environment:
      NETLIFY_AUTH_TOKEN:
        from_secret: NETLIFY_AUTH_TOKEN
      NETLIFY_SITE_ID:
        from_secret: NETLIFY_SITE_ID
    commands:
      - bash deploy.sh

  - name: Notification
    image: plugins/slack
    when:
      status:
        - success
        - failure
    settings:
      webhook:
        from_secret: SLACK_TAMETO
      channel: tameto-builds
      link_names: true
      template: >
        {{#success build.status}}
          {{repo.name}}: :white_check_mark: Build #{{build.number}} succeeded!
          {{build.link}}
        {{else}}
          {{repo.name}} :x: Build #{{build.number}} failed. Fix me please.
          {{build.link}}
        {{/success}}

volumes:
  - name: cache
    host:
      path: /var/lib/cache
