---
label: Project
hide_body: false
fields:
- type: text
  name: template
  label: template
  hidden: true
  default: project
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- type: text
  name: title
  label: Title
- type: image_gallery
  name: gallery
  label: Gallery
pages:
- content/projects/lonely-hearts.md
