---
label: Project
hide_body: false
fields:
- type: text
  name: template
  label: template
  hidden: true
  default: project
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- type: text
  name: title
  label: Title
- type: image_gallery
  name: gallery
  label: Gallery
pages:
- content/projects/abstand-bitte-festival.md
- content/projects/an-i-with-two-pupils.md
- content/projects/becoming-anima.md
- content/projects/boa.md
- content/projects/gut-buddies.md
- content/projects/like-a-horse.md
- content/projects/lonely-hearts.md
- content/projects/misc.md
- content/projects/take-a-workshop.md
- content/projects/the-elephant-workshop.md
- content/projects/the-whilst-walking-tour.md
